// <auto-generated />
using DataAccessLayerCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayerCore.Migrations
{
    [DbContext(typeof(TravelListContext))]
    [Migration("20201018085652_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayerCore.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("TravelListID");

                    b.HasKey("ItemID");

                    b.HasIndex("TravelListID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DataAccessLayerCore.Models.TravelList", b =>
                {
                    b.Property<int>("TravelListID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("TravelListID");

                    b.ToTable("TravelLists");
                });

            modelBuilder.Entity("DataAccessLayerCore.Models.Item", b =>
                {
                    b.HasOne("DataAccessLayerCore.Models.TravelList", "TravelList")
                        .WithMany("Items")
                        .HasForeignKey("TravelListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
